version: "3"

services:
  rustapp:
    build: ./rust
    # volumes:
    #   - ./web:/usr/src/app
    ports:
      - "3000:3000"
  vscode:
    environment:
        APP_PORT: '8080'
        PASSWORD: alohamora
        USE_HTTPS: 'false'
    image: 'ruanbekker/vscode-server:slim'
    ports:
        - '8080:8080'